"""
Enhanced Report Generator for Medical Predictions
- Automatic PDF generation after X-ray/MRI predictions
- Professional medical report format
- Includes patient information, predictions, recommendations
- Embeds X-ray/MRI images and heatmaps
- Uses FPDF for PDF generation

Author: AI-Enhanced Medical Imaging System
Date: 2025-11-13
"""

import os
from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Dict, List, Optional
import logging

try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False
    logging.warning("FPDF not available - PDF generation disabled")

from PIL import Image

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class EnhancedMedicalReportPDF(FPDF):
    """Custom PDF class with header and footer"""
    
    def __init__(self):
        super().__init__()
        self.logo_path = None
    
    def header(self):
        """PDF header"""
        # Logo if available
        if self.logo_path and os.path.exists(self.logo_path):
            self.image(self.logo_path, 10, 8, 25)
        
        # Title
        self.set_font('Arial', 'B', 20)
        self.set_text_color(42, 144, 226)  # Blue color
        self.cell(0, 10, 'HealthGuard Medical Report', ln=True, align='C')
        
        # Subtitle
        self.set_font('Arial', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, 'AI-Powered Disease Detection System', ln=True, align='C')
        
        # Line break
        self.ln(5)
        
        # Draw line
        self.set_draw_color(42, 144, 226)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)
    
    def footer(self):
        """PDF footer"""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        
        # Page number
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}}', align='C')
        
        # Footer text
        self.ln(4)
        self.set_font('Arial', 'I', 7)
        self.cell(0, 5, 'This report is generated by AI and should be reviewed by a medical professional', align='C')
    
    def chapter_title(self, title: str, color=(42, 144, 226)):
        """Add chapter title"""
        self.set_font('Arial', 'B', 14)
        self.set_text_color(*color)
        self.cell(0, 10, title, ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)
    
    def section_title(self, title: str):
        """Add section title"""
        self.set_font('Arial', 'B', 12)
        self.set_text_color(0, 0, 0)
        self.cell(0, 8, title, ln=True)
        self.ln(1)
    
    def add_info_box(self, label: str, value: str, width=90):
        """Add information box"""
        self.set_font('Arial', 'B', 10)
        self.cell(50, 7, label + ':', border=0)
        self.set_font('Arial', '', 10)
        self.cell(width, 7, str(value), border=0, ln=True)
    
    def add_prediction_box(self, disease: str, confidence: float, severity: str):
        """Add prediction box with color coding"""
        # Color based on severity
        if severity == 'high':
            bg_color = (255, 200, 200)  # Light red
        elif severity == 'moderate':
            bg_color = (255, 255, 200)  # Light yellow
        else:
            bg_color = (200, 255, 200)  # Light green
        
        # Draw box
        self.set_fill_color(*bg_color)
        self.set_font('Arial', 'B', 11)
        self.cell(90, 8, disease, border=1, fill=True)
        
        self.set_font('Arial', '', 10)
        self.cell(50, 8, f'Confidence: {confidence:.1f}%', border=1, fill=True)
        
        self.set_font('Arial', 'B', 10)
        self.set_text_color(200, 0, 0) if severity == 'high' else self.set_text_color(0, 0, 0)
        self.cell(0, 8, f'Severity: {severity.upper()}', border=1, fill=True, ln=True)
        self.set_text_color(0, 0, 0)


class EnhancedReportGenerator:
    """Generate comprehensive medical reports with PDF"""
    
    def __init__(self):
        self.fpdf_available = FPDF_AVAILABLE
        self.reports_dir = Path("app/static/reports")
        self.reports_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_xray_report(self, 
                            patient_info: Dict,
                            prediction_result: Dict,
                            image_path: Optional[str] = None,
                            heatmap_path: Optional[str] = None) -> Optional[str]:
        """
        Generate comprehensive X-ray/MRI report
        
        Args:
            patient_info: Dictionary with patient information
            prediction_result: Dictionary with prediction results
            image_path: Path to original X-ray/MRI image
            heatmap_path: Path to heatmap overlay image
            
        Returns:
            Path to generated PDF report or None
        """
        if not self.fpdf_available:
            logger.warning("FPDF not available - cannot generate PDF")
            return None
        
        try:
            # Create PDF
            pdf = EnhancedMedicalReportPDF()
            pdf.alias_nb_pages()
            pdf.add_page()
            
            # Patient Information Section
            pdf.chapter_title('PATIENT INFORMATION', (42, 144, 226))
            pdf.set_font('Arial', '', 11)
            
            pdf.add_info_box('Patient Name', patient_info.get('name', 'N/A'))
            pdf.add_info_box('Patient ID', patient_info.get('id', 'N/A'))
            pdf.add_info_box('Age', f"{patient_info.get('age', 'N/A')} years")
            pdf.add_info_box('Gender', patient_info.get('gender', 'N/A'))
            pdf.add_info_box('Report Date', datetime.now().strftime('%B %d, %Y at %I:%M %p'))
            pdf.add_info_box('Report Type', patient_info.get('scan_type', 'X-Ray Analysis'))
            
            pdf.ln(5)
            
            # Diagnostic Analysis Section
            pdf.chapter_title('DIAGNOSTIC ANALYSIS', (42, 144, 226))
            
            # Analysis method
            method = prediction_result.get('method', 'N/A')
            model_type = prediction_result.get('model_type', 'N/A')
            pdf.set_font('Arial', 'I', 9)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(0, 6, f'Analysis Method: {model_type} ({method})', ln=True)
            pdf.set_text_color(0, 0, 0)
            pdf.ln(3)
            
            # Primary Finding
            pdf.section_title('Primary Finding:')
            primary_disease = prediction_result.get('primary_disease', 'Unknown')
            primary_confidence = prediction_result.get('confidence_percentage', 0)
            
            pdf.set_font('Arial', 'B', 14)
            if primary_disease == "No Disease Detected":
                pdf.set_text_color(0, 150, 0)  # Green
            else:
                pdf.set_text_color(200, 0, 0)  # Red
            pdf.cell(0, 10, primary_disease, ln=True)
            pdf.set_text_color(0, 0, 0)
            
            pdf.set_font('Arial', '', 11)
            pdf.cell(0, 6, f'Confidence Level: {primary_confidence:.1f}%', ln=True)
            pdf.ln(5)
            
            # Detected Diseases
            detected_diseases = prediction_result.get('detected_diseases', [])
            if detected_diseases and detected_diseases[0].get('disease') != 'Normal':
                pdf.section_title('Detected Abnormalities:')
                
                for disease_info in detected_diseases:
                    disease = disease_info.get('disease', 'Unknown')
                    confidence = disease_info.get('percentage', 0)
                    severity = disease_info.get('severity', 'moderate')
                    
                    pdf.add_prediction_box(disease, confidence, severity)
                
                pdf.ln(5)
            
            # Medical Images
            if image_path and os.path.exists(image_path):
                pdf.chapter_title('MEDICAL IMAGES', (42, 144, 226))
                
                # Prepare images
                try:
                    # Original image
                    pdf.section_title('Original X-Ray/MRI:')
                    self._add_image_to_pdf(pdf, image_path, width=180)
                    pdf.ln(5)
                    
                    # Heatmap
                    if heatmap_path and os.path.exists(heatmap_path):
                        pdf.section_title('AI Analysis Heatmap:')
                        self._add_image_to_pdf(pdf, heatmap_path, width=180)
                        pdf.ln(5)
                        
                except Exception as e:
                    logger.warning(f"Could not add images to PDF: {e}")
            
            # Recommendations
            pdf.add_page()
            pdf.chapter_title('MEDICAL RECOMMENDATIONS', (42, 144, 226))
            
            recommendations = prediction_result.get('recommendations', [])
            if recommendations:
                pdf.set_font('Arial', '', 11)
                
                for i, recommendation in enumerate(recommendations, 1):
                    # Clean emoji from recommendation for PDF
                    clean_rec = recommendation.encode('ascii', 'ignore').decode('ascii').strip()
                    if clean_rec:
                        pdf.multi_cell(0, 6, f'{i}. {clean_rec}')
                        pdf.ln(2)
            else:
                pdf.set_font('Arial', '', 11)
                pdf.multi_cell(0, 6, 'No specific recommendations available. Please consult with a healthcare professional.')
            
            pdf.ln(10)
            
            # Disclaimer
            pdf.chapter_title('IMPORTANT DISCLAIMER', (200, 0, 0))
            pdf.set_font('Arial', 'I', 9)
            pdf.set_text_color(100, 0, 0)
            disclaimer_text = (
                "This report is generated by an AI-powered diagnostic system and should NOT be used as a "
                "substitute for professional medical advice, diagnosis, or treatment. Always seek the advice "
                "of your physician or other qualified health provider with any questions you may have regarding "
                "a medical condition. The AI system has limitations and may produce false positives or false "
                "negatives. All findings should be confirmed by a licensed radiologist or medical professional."
            )
            pdf.multi_cell(0, 5, disclaimer_text)
            pdf.set_text_color(0, 0, 0)
            
            pdf.ln(10)
            
            # Additional Information
            pdf.section_title('Additional Notes:')
            pdf.set_font('Arial', '', 9)
            pdf.cell(0, 5, f'Doctor/Technician: {patient_info.get("doctor_name", "Not Specified")}', ln=True)
            pdf.cell(0, 5, f'Institution: {patient_info.get("institution", "HealthGuard Medical Center")}', ln=True)
            pdf.cell(0, 5, f'Report ID: {patient_info.get("report_id", datetime.now().strftime("%Y%m%d%H%M%S"))}', ln=True)
            
            # Save PDF
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            patient_name_clean = patient_info.get('name', 'patient').replace(' ', '_')
            filename = f'medical_report_{patient_name_clean}_{timestamp}.pdf'
            output_path = self.reports_dir / filename
            
            pdf.output(str(output_path))
            logger.info(f"✅ Report generated: {output_path}")
            
            return str(output_path)
            
        except Exception as e:
            logger.error(f"❌ Error generating report: {e}")
            return None
    
    def _add_image_to_pdf(self, pdf: FPDF, image_path: str, width: int = 180):
        """Add image to PDF with proper formatting"""
        try:
            # Open and convert image
            img = Image.open(image_path)
            
            # Convert to RGB if needed
            if img.mode not in ['RGB', 'L']:
                img = img.convert('RGB')
            
            # Calculate height maintaining aspect ratio
            aspect_ratio = img.height / img.width
            height = width * aspect_ratio
            
            # Limit height
            max_height = 120
            if height > max_height:
                height = max_height
                width = height / aspect_ratio
            
            # Center image
            x = (210 - width) / 2  # A4 width is 210mm
            
            # Add image
            pdf.image(image_path, x=x, y=pdf.get_y(), w=width, h=height)
            pdf.ln(height + 2)
            
        except Exception as e:
            logger.warning(f"Could not add image {image_path}: {e}")
            pdf.set_font('Arial', 'I', 9)
            pdf.cell(0, 6, f'[Image could not be loaded: {os.path.basename(image_path)}]', ln=True)
    
    def generate_report_bytes(self, 
                             patient_info: Dict,
                             prediction_result: Dict,
                             image_path: Optional[str] = None,
                             heatmap_path: Optional[str] = None) -> Optional[bytes]:
        """
        Generate report and return as bytes (for direct download)
        
        Args:
            patient_info: Dictionary with patient information
            prediction_result: Dictionary with prediction results
            image_path: Path to original image
            heatmap_path: Path to heatmap image
            
        Returns:
            PDF bytes or None
        """
        report_path = self.generate_xray_report(
            patient_info, prediction_result, image_path, heatmap_path
        )
        
        if report_path and os.path.exists(report_path):
            with open(report_path, 'rb') as f:
                return f.read()
        
        return None


# Global instance
enhanced_report_generator = EnhancedReportGenerator()


def generate_medical_report(patient_info: Dict, 
                           prediction_result: Dict,
                           image_path: Optional[str] = None,
                           heatmap_path: Optional[str] = None) -> Optional[str]:
    """
    Convenience function to generate medical report
    
    Args:
        patient_info: Patient information dictionary
        prediction_result: Prediction results dictionary
        image_path: Path to medical image
        heatmap_path: Path to heatmap overlay
        
    Returns:
        Path to generated PDF or None
    """
    return enhanced_report_generator.generate_xray_report(
        patient_info, prediction_result, image_path, heatmap_path
    )


if __name__ == "__main__":
    # Test report generation
    print("Testing Enhanced Report Generator...")
    print(f"FPDF Available: {FPDF_AVAILABLE}")
    
    if FPDF_AVAILABLE:
        # Sample data
        test_patient = {
            'name': 'John Doe',
            'id': 'P12345',
            'age': 45,
            'gender': 'Male',
            'scan_type': 'Chest X-Ray',
            'doctor_name': 'Dr. Smith',
            'institution': 'HealthGuard Medical Center'
        }
        
        test_prediction = {
            'primary_disease': 'Pneumonia',
            'confidence': 0.87,
            'confidence_percentage': 87.0,
            'detected_diseases': [
                {'disease': 'Pneumonia', 'confidence': 0.87, 'percentage': 87.0, 'severity': 'high'},
                {'disease': 'Consolidation', 'confidence': 0.65, 'percentage': 65.0, 'severity': 'moderate'}
            ],
            'recommendations': [
                'Urgent: Start antibiotic treatment',
                'Supportive care with rest and hydration',
                'Monitor temperature and oxygen levels'
            ],
            'method': 'deep_learning',
            'model_type': 'Enhanced EfficientNet'
        }
        
        report_path = generate_medical_report(test_patient, test_prediction)
        print(f"Test report generated: {report_path}")
